name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-24.04

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install pnpm
      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      # Step 4: Verify pnpm installation
      - name: Verify pnpm
        run: pnpm --version

      # Step 5: Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Step 6: Run Prettier
      - name: Check format with Prettier
        run: pnpm prettier --check .

      # Step 7: Run ESLint
      - name: Lint with ESLint
        run: pnpm lint

      # Step 8: Check types with TypeScript
      - name: Check types with TypeScript
        run: pnpm tsc --noEmit -p tsconfig.build.json

      # Step 9: Build the project
      - name: Build Next.js app
        run: pnpm build
